title: Xiaoshan Yang
url: "https://yangxs.ac.cn"
baseurl: "/yangxs.github.io"

markdown: kramdown
ins_logo: "./casia.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/YangXS"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/yangxs.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
